version: '3'

services:

  ollama-container:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ./:/data
    ports:
      - 11435:11435
    command: /bin/bash -c "pip install ollama && ollama serve"

  python-app:
    image: langchain
    container_name: python-app
    ports:
      - 8501:8501  
    command: streamlit run app.py --server.port=8501  