version: '3'

services:

  ollama-container:
    image: ollama/ollama
    volumes:
      - ./:/data
    ports:
      - 11434:11434

  python-app:
    image: langchain
    ports:
      - 8501:8501    