version: '3'

services:

  ollama-container:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ./:/data
    ports:
      - 11435:11435
    command: ollama serve

  python-app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8501:8501"  