version: '3'

services:

  ollama-container:
    image: sandhyadiagonal/medium:ollama-container
    container_name: ollama-container
    volumes:
      - ./:/data
    ports:
      - 11434:11434

  python-app:
    image: sandhyadiagonal/medium:python-app
    container_name: python-app
    ports:
      - 8501:8501    